using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToolModiSAO.Dati
{
    public class Cod_UUOO
    {
        public Dictionary<string, int> reparti = new Dictionary<string, int>
        {
            { " ", 000 },
            { "DA", 100 },
            { "DA - SPP", 120 },
            { "DA - CONSULENTE GIURIDICO", 150 },
            { "DA - PCN", 140 },
            { "DA - SPP - SICUREZZA SUL LAVORO", 122 },
            { "DA - URP", 130 },
            { "DA - UCS", 160 },
            { "DA - SPP - AMBIENTE", 121 },
            { "DA - SEGRETERIA DA", 110 },
            { "VDA", 200 },
            { "VDA - SAG", 250 },
            { "VDA - SAG PROTOCOLLO E ARCHIVIO", 252 },
            { "VDA - SPE", 220 },
            { "VDA - SANITARIA", 240 },
            { "VDA - SPE - PERSONALE MILITARE", 222 },
            { "VDA - SPE - PERSONALE CIVILE", 221 },
            { "VDA - SAQ", 230 },
            { "VDA - SAO", 260 },
            { "VDA - SEGRETERIA VDA", 210 },
            { "VDA - SAG - MENSA", 251 },
            { "RAM - ATTIVITÀ NEGOZIALI - CONTRATTI E PERMUTE", 322 },
            { "RAM - GESTIONE PATRIMONIALE - SETTORE SALA RICEZIONE", 343 },
            { "RAM - GESTIONE PATRIMONIALE - SETTORE ECONOMATO", 342 },
            { "RAM - SEGRETERIA RAM", 310 },
            { "RAM - GESTIONE PATRIMONIALE MAGAZZINI - SUPPORTO/TRANSITO/FUORI USO", 341 },
            { "RAM - GESTIONE PATRIMONIALE - ECONOMATO E SALA RICEZIONE", 344 },
            { "RAM - GESTIONE PATRIMONIALE", 340 },
            { "RAM", 300 },
            { "RAM - ATTIVITÀ NEGOZIALI - ECONOMIE", 321 },
            { "RAM - ATTIVITÀ NEGOZIALI", 320 },
            { "RAM - GESTIONE FINANZIARIA", 330 },
            { "RAM - GESTIONE FINANZIARIA ESECUZIONE E LIQUIDAZIONE - CONTRATTI ED ECONOMIE", 331 },
            { "RAM - GESTIONE FINANZIARIA ESECUZIONE E LIQUIDAZIONE - COMPETENZE AL PERSONALE", 332 },
            { "RAM - GESTIONE FINANZIARIA - GESTIONE FINANZIARIA", 333 },
            { "RMN - BACINI", 440 },
            { "RMN - SSN AM", 421 },
            { "RMN - SSN MA", 423 },
            { "RMN - SSN - IEB", 422 },
            { "RMN - SSN - SDL E CND", 425 },
            { "RMN - SSC", 430 },
            { "RMN - SSC SISTEMI ELETTROMECCANICI - ARMA E SENSORI", 431 },
            { "RMN - SSC - SISTEMI ELETTRONICI E TLC", 432 },
            { "RMN - SSN - SCAFO E ALLESTIMENTI", 424 },
            { "RMN - BACINI - GO53", 441 },
            { "RMN - BACINI - GO58", 442 },
            { "RMN - PROGRAMMI - NAVALI", 450 },
            { "RMN - PROGRAMMI NAVALI - MATERIALI SPECIALI", 451 },
            { "RMN - PROGRAMMI - NAVALI PIANIFICAZIONE", 453 },
            { "RMN - PROGRAMMI - NAVALI CONTROLLO", 452 },
            { "RMN - BACINI - GO60", 443 },
            { "RMN - SEGRETERIA - RMN", 410 },
            { "RMN - SSN", 420 },
            { "RMN", 400 },
            { "RSTA - INFRASTRUTTURE", 520 },
            { "RSTA - INFRASTRUTTURE STRUTTURE", 521 },
            { "RSTA - SERVIZI ARSENALE", 530 },
            { "RSTA - SERVIZI ARSENALE - TRASPORTI E SOLLEVAMENTI", 531 },
            { "RSTA - SERVIZI ARSENALE - RETI E IMPIANTI ELETTRICI", 532 },
            { "RSTA - SUPPORTI INFORMATICI", 540 },
            { "RSTA - SUPPORTI INFORMATICI - GESTIONE RISORSE INFORMATICHE", 541 },
            { "RSTA - SUPPORTI - INFORMATICI GESTIONE SOFTWARE", 542 },
            { "RSTA", 500 },
            { "RSTA - SERVIZI ARSENALE - SUPPORTI E MANUTENZIONE EDILE", 533 },
            { "RSTA - INFRASTRUTTURE IMPIANTI", 522 },
            { "RSTA - SEGRETERIA RSTA", 510 },
            { "RCLE", 600 },
            { "RCLE - SEGRETERIA - RCLE", 610 },
            { "RCLE - VERIFICHE DI CONFORMITÀ", 630 },
            { "RCLE - PIANIFICAZIONE - ESECUTIVA TERRESTRE", 623 },
            { "RCLE - PIANIFICAZIONE - ESECUTIVA NAVALE ED ALIENAZIONI", 622 },
            { "RCLE - STUDI ED ESPERIENZE", 640 },
            { "RCLE - PIANIFICAZIONE ESECUTIVA", 620 },
            { "RCLE - PIANIFICAZIONE ESECUTIVA PIANIFICAZIONE - CONTROLLO E PERMUTE", 621 }
        };
    }
}